CREATE TABLE ROLES(
	ID_ROL INT PRIMARY KEY IDENTITY(1,1),
	NAME_ROL VARCHAR(15) NOT NULL
);
CREATE TABLE PERMISSION(
	ID_PER INT PRIMARY KEY IDENTITY(1,1),
	NAME_PER VARCHAR(50) NOT NULL,
	DESCRIPTION_PER VARCHAR(MAX)
);
CREATE TABLE USERS(
	ID_USE INT PRIMARY KEY, --CEDULA
	PASS_USE VARCHAR(MAX) NOT NULL,
	NAME_USE VARCHAR(50) NOT NULL,
	EMAIL_USE VARCHAR(50),
	PHONE1_USE VARCHAR(10),
	PHONE2_USE VARCHAR(10),
	ID_ROL INT NOT NULL 
);
CREATE TABLE USERSXPERMISSION(
	ID_USEPER INT IDENTITY(1,1) PRIMARY KEY
	ID_PER INT NOT NULL,
	ID_USE INT NOT NULL,
)
CREATE TABLE COMPANY(
	ID_COM INT IDENTITY(1,1),
	NIT VARCHAR(30) NOT NULL,
	ID_USE_RESPO INT NOT NULL,
	NAME_COM VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID_COM, NIT)
)
CREATE TABLE LICENCIA(
	ID_LIC INT IDENTITY(1,1) PRIMARY KEY,
	DATE_EXPIRED DATETIME NOT NULL,
	ID_USE INT NOT NULL
	ID_COMPANY int not null
)

ALTER TABLE USERS ADD CONSTRAINT fk_UserRol FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL);
ALTER TABLE USERSXPERMISSION ADD CONSTRAINT fk_useper_per FOREIGN KEY(ID_PER) REFERENCES PERMISSION(ID_PER);
ALTER TABLE USERSXPERMISSION ADD CONSTRAINT fk_useper_user FOREIGN KEY(ID_USE) REFERENCES USERS(ID_USE);
ALTER TABLE COMPANY ADD CONSTRAINT fk_company_user FOREIGN KEY(ID_USE_RESPO) REFERENCES USERS(ID_USE);
ALTER TABLE LICENCIA ADD CONSTRAINT fk_licencia_user FOREIGN KEY(ID_USE) REFERENCES USERS(ID_USE);
ALTER TABLE LICENCIA ADD CONSTRAINT fk_licencia_company FOREIGN KEY(ID_COMPANY) REFERENCES COMPANY(ID_COM);